#!/usr/bin/env bash

set -e

nixos-generate-config --root /mnt

cp configuration.nix /mnt/etc/nixos/
nixos-install

echo "*************************************"
echo "Rebooting machine, don't be scared ;)"
echo "*************************************"

sleep 3

reboot
