#!/usr/bin/env bash

set -e

cp configuration.nix /etc/nixos/
nixos-rebuild switch

echo "*************************************"
echo "Rebooting machine, don't be scared ;)"
echo "*************************************"

sleep 3

reboot
