#!/usr/bin/env bash

set -e

sudo rm /etc/nixos/configuration.nix && sudo ln configuration.nix /etc/nixos/

if [[ $(ssh-add -L) == *no\ ident* ]]; then
  echo "Add some ssh keys, dawg!"
  exit 1
fi

{
  echo $HOME/workspace/concourse git@github.com:concourse/concourse.git
  echo $HOME/workspace/bosh-lite git@github.com:cloudfoundry/bosh-lite.git
  echo $HOME/workspace/garden-linux-release git@github.com:cloudfoundry-incubator/garden-linux-release.git
} | while read repo source; do
  if [[ ! -d $repo ]]; then
    pushd $(dirname $repo)
    git clone $source --recursive
    popd
  fi
done

mkdir -p $HOME/bin

mkdir /tmp/duet
pushd /tmp/duet
wget https://github.com/git-duet/git-duet/releases/download/0.3.0/linux_amd64.tar.gz
tar -zxf linux_amd64.tar.gz
rm linux_amd64.tar.gz
mv * $HOME/bin
popd
rm -rf /tmp/duet

export GOPATH=$HOME/go
mkdir -p $HOME/go
go get -u github.com/onsi/ginkgo/ginkgo

pushd stowaways
./load_dotfiles
popd
